import type {
  Account,
  AuditLog,
  Client,
  Communication,
  Decision,
  Expense,
  Maintenance,
  MaintenancePayment,
  Milestone,
  Payment,
  Project,
  ProjectFile,
  Prospect,
  Service,
  Task,
  User,
} from "./types";

export const currentUser: User = {
  id: "u-ezra",
  email: "ezra@me.dev",
  name: "Ezra",
  role: "admin",
  is_active: true,
  color: "grow",
  avatar_emoji: "🪐",
};

export const users: User[] = [
  {
    id: "u-marcos",
    email: "marcos@me.dev",
    name: "Marcos",
    role: "admin",
    is_active: true,
    color: "ops",
    avatar_emoji: "🎸",
  },
  currentUser,
];

export const accounts: Account[] = [
  { id: "a-mp-m", name: "MP Marcos", owner_id: "u-marcos", type: "billetera_digital", currency: "ARS", is_active: true },
  { id: "a-usd-m", name: "Cuenta Marcos USD", owner_id: "u-marcos", type: "banco", currency: "USD", is_active: true },
  { id: "a-bbva-e", name: "BBVA Ezra", owner_id: "u-ezra", type: "banco", currency: "ARS", is_active: true },
  { id: "a-usd-e", name: "Cuenta Ezra USD", owner_id: "u-ezra", type: "banco", currency: "USD", is_active: true },
  { id: "a-caja-ars", name: "Caja Común ARS", owner_id: "u-marcos", type: "efectivo", currency: "ARS", is_active: true },
  { id: "a-caja-usd", name: "Caja Común USD", owner_id: "u-marcos", type: "efectivo", currency: "USD", is_active: true },
];

export const clients: Client[] = [
  {
    id: "c-01",
    name: "Cervecería Bachmann",
    industry: "Gastronomía",
    contact: "Sofía Bachmann",
    phone: "+54 9 294 412 3344",
    email: "sofi@bachmann.beer",
    preferred_currency: "ARS",
    notes: "Cerveza artesanal, Bariloche. Muy orientados a UX.",
    is_active: true,
    created_at: "2025-11-02",
  },
  {
    id: "c-02",
    name: "Estudio Trama",
    industry: "Arquitectura",
    contact: "Iván Menéndez",
    phone: "+54 9 11 5500 2211",
    email: "ivan@trama.ar",
    preferred_currency: "USD",
    is_active: true,
    created_at: "2025-12-11",
  },
  {
    id: "c-03",
    name: "Panadería La Veleta",
    industry: "Gastronomía",
    contact: "Lucía Reyna",
    phone: "+54 9 294 433 9912",
    email: "hola@laveleta.com",
    preferred_currency: "ARS",
    is_active: true,
    created_at: "2026-01-07",
  },
  {
    id: "c-04",
    name: "Clínica Andina",
    industry: "Salud",
    contact: "Dr. Marcelo Ríos",
    phone: "+54 9 294 455 1010",
    email: "m.rios@clinicaandina.ar",
    preferred_currency: "ARS",
    is_active: true,
    created_at: "2026-02-14",
  },
  {
    id: "c-05",
    name: "Kiosco Nómade",
    industry: "Retail",
    contact: "Juanjo Silva",
    phone: "+54 9 294 466 7788",
    email: "juanjo@nomade.ar",
    preferred_currency: "ARS",
    is_active: false,
    created_at: "2025-08-20",
  },
];

export const projects: Project[] = [
  {
    id: "p-01",
    client_id: "c-01",
    name: "Chatbot pedidos Bachmann",
    description: "Bot de WhatsApp para tomar pedidos y reservas.",
    status: "activo",
    phase: "desarrollo",
    start_date: "2026-02-10",
    end_date: "2026-05-15",
    responsible_id: "u-marcos",
    total_amount: 1_850_000,
    currency: "ARS",
    created_at: "2026-02-10",
  },
  {
    id: "p-02",
    client_id: "c-02",
    name: "Portal de proyectos Trama",
    description: "Web app para gestionar expedientes de obra.",
    status: "activo",
    phase: "diseno",
    start_date: "2026-03-04",
    responsible_id: "u-ezra",
    total_amount: 4200,
    currency: "USD",
    created_at: "2026-03-04",
  },
  {
    id: "p-03",
    client_id: "c-03",
    name: "Panel inventario La Veleta",
    description: "Panel web simple para stock diario.",
    status: "activo",
    phase: "soporte",
    start_date: "2025-10-15",
    end_date: "2026-01-15",
    responsible_id: "u-ezra",
    total_amount: 780_000,
    currency: "ARS",
    created_at: "2025-10-15",
  },
  {
    id: "p-04",
    client_id: "c-04",
    name: "Chatbot turnos Clínica Andina",
    description: "Bot de turnos con calendario integrado.",
    status: "activo",
    phase: "descubrimiento",
    start_date: "2026-04-01",
    responsible_id: "u-marcos",
    total_amount: 2_300_000,
    currency: "ARS",
    created_at: "2026-04-01",
  },
  {
    id: "p-05",
    client_id: "c-01",
    name: "Landing menú estacional",
    description: "Landing estática con menú del mes.",
    status: "completado",
    phase: "soporte",
    start_date: "2025-09-01",
    end_date: "2025-10-15",
    responsible_id: "u-marcos",
    total_amount: 420_000,
    currency: "ARS",
    created_at: "2025-09-01",
  },
];

export const tasks: Task[] = [
  {
    id: "t-01",
    project_id: "p-01",
    title: "Revisar intents del bot con Marcos",
    assigned_to: "u-ezra",
    priority: "alta",
    status: "pendiente",
    due_date: "2026-04-16",
  },
  {
    id: "t-02",
    project_id: "p-01",
    title: "Grabar demo para cliente",
    assigned_to: "u-marcos",
    priority: "media",
    status: "pendiente",
    due_date: "2026-04-17",
  },
  {
    id: "t-03",
    project_id: "p-02",
    title: "Entregar wireframes v2",
    assigned_to: "u-ezra",
    priority: "urgente",
    status: "en_progreso",
    due_date: "2026-04-16",
  },
  {
    id: "t-04",
    project_id: "p-03",
    title: "Subir backup mensual a Drive",
    assigned_to: "u-ezra",
    priority: "baja",
    status: "pendiente",
    due_date: "2026-04-20",
  },
  {
    id: "t-05",
    project_id: "p-04",
    title: "Primera reunión de descubrimiento",
    assigned_to: "u-marcos",
    priority: "alta",
    status: "pendiente",
    due_date: "2026-04-18",
  },
  {
    id: "t-06",
    project_id: "p-02",
    title: "Configurar Supabase en proyecto",
    assigned_to: "u-ezra",
    priority: "media",
    status: "completada",
    due_date: "2026-04-10",
    completed_at: "2026-04-09",
  },
];

export const payments: Payment[] = [
  {
    id: "pay-01",
    project_id: "p-01",
    description: "Adelanto 50%",
    amount: 925_000,
    currency: "ARS",
    scheduled_date: "2026-02-15",
    status: "cobrado",
    paid_at: "2026-02-14",
    payment_method: "transferencia",
    collected_by: "u-marcos",
    account_id: "a-mp-m",
  },
  {
    id: "pay-02",
    project_id: "p-01",
    description: "Entrega final",
    amount: 925_000,
    currency: "ARS",
    scheduled_date: "2026-05-15",
    status: "pendiente",
  },
  {
    id: "pay-03",
    project_id: "p-02",
    description: "Hito 1 — discovery",
    amount: 1200,
    currency: "USD",
    scheduled_date: "2026-03-10",
    status: "cobrado",
    paid_at: "2026-03-09",
    payment_method: "wise",
    collected_by: "u-ezra",
    account_id: "a-usd-e",
  },
  {
    id: "pay-04",
    project_id: "p-02",
    description: "Hito 2 — diseño",
    amount: 1500,
    currency: "USD",
    scheduled_date: "2026-04-20",
    status: "pendiente",
  },
  {
    id: "pay-05",
    project_id: "p-02",
    description: "Hito 3 — entrega",
    amount: 1500,
    currency: "USD",
    scheduled_date: "2026-06-15",
    status: "pendiente",
  },
  {
    id: "pay-06",
    project_id: "p-04",
    description: "Adelanto",
    amount: 1_150_000,
    currency: "ARS",
    scheduled_date: "2026-04-18",
    status: "pendiente",
  },
  {
    id: "pay-07",
    project_id: "p-05",
    description: "Pago único",
    amount: 420_000,
    currency: "ARS",
    scheduled_date: "2025-10-10",
    status: "cobrado",
    paid_at: "2025-10-10",
    payment_method: "transferencia",
    collected_by: "u-marcos",
    account_id: "a-caja-ars",
  },
];

export const maintenances: Maintenance[] = [
  {
    id: "m-01",
    project_id: "p-03",
    description: "Soporte panel inventario",
    amount: 60_000,
    currency: "ARS",
    billing_day: 5,
  },
  {
    id: "m-02",
    project_id: "p-05",
    description: "Hosting + actualizaciones",
    amount: 45_000,
    currency: "ARS",
    billing_day: 10,
  },
];

export const maintenancePayments: MaintenancePayment[] = [
  { id: "mp-01", maintenance_id: "m-01", period: "2026-04", scheduled_date: "2026-04-05", status: "cobrado", paid_at: "2026-04-05", account_id: "a-bbva-e" },
  { id: "mp-02", maintenance_id: "m-02", period: "2026-04", scheduled_date: "2026-04-10", status: "pendiente" },
  { id: "mp-03", maintenance_id: "m-01", period: "2026-05", scheduled_date: "2026-05-05", status: "pendiente" },
  { id: "mp-04", maintenance_id: "m-02", period: "2026-05", scheduled_date: "2026-05-10", status: "pendiente" },
];

export const expenses: Expense[] = [
  { id: "e-01", name: "Vercel Pro", category: "Infra", cost: 20, currency: "USD", frequency: "mensual", next_due_date: "2026-04-22" },
  { id: "e-02", name: "Supabase Pro", category: "Infra", cost: 25, currency: "USD", frequency: "mensual", next_due_date: "2026-04-28" },
  { id: "e-03", name: "OpenAI API", category: "IA", cost: 150, currency: "USD", frequency: "mensual", next_due_date: "2026-05-01", project_id: "p-01" },
  { id: "e-04", name: "Figma Organization", category: "Diseño", cost: 45, currency: "USD", frequency: "mensual", next_due_date: "2026-04-19" },
  { id: "e-05", name: "Dominio .com.ar", category: "Infra", cost: 3500, currency: "ARS", frequency: "anual", next_due_date: "2026-11-02" },
  { id: "e-06", name: "WhatsApp Business API", category: "Canal", cost: 80, currency: "USD", frequency: "mensual", next_due_date: "2026-04-25", project_id: "p-01" },
];

export const prospects: Prospect[] = [
  {
    id: "pr-01",
    name: "Cervecería del Lago",
    company: "Del Lago SRL",
    source: "referido",
    responsible_id: "u-marcos",
    estimated_amount: 1_500_000,
    currency: "ARS",
    stage: "contacto_inicial",
    next_step: "Reunión diagnóstico",
    next_step_date: "2026-04-22",
    notes: "Viene por referencia de Bachmann.",
  },
  {
    id: "pr-02",
    name: "Vinería Alta Patagonia",
    company: "Vinos AP",
    source: "redes",
    responsible_id: "u-marcos",
    estimated_amount: 2100,
    currency: "USD",
    stage: "propuesta_enviada",
    next_step: "Seguir propuesta",
    next_step_date: "2026-04-18",
  },
  {
    id: "pr-03",
    name: "Estudio Norte",
    source: "contacto_directo",
    responsible_id: "u-ezra",
    estimated_amount: 3200,
    currency: "USD",
    stage: "negociacion",
    next_step: "Ajustar alcance",
    next_step_date: "2026-04-19",
  },
  {
    id: "pr-04",
    name: "Café Mandarina",
    source: "evento",
    responsible_id: "u-marcos",
    estimated_amount: 650_000,
    currency: "ARS",
    stage: "cerrado_ganado",
    notes: "Se convierte a cliente esta semana.",
  },
  {
    id: "pr-05",
    name: "Inmobiliaria Pichi",
    source: "referido",
    responsible_id: "u-ezra",
    stage: "cerrado_perdido",
    notes: "No tenían presupuesto.",
  },
];

export const services: Service[] = [
  {
    id: "s-01",
    name: "Chatbot WhatsApp comercial",
    description: "Bot conversacional con IA, integración a tu catálogo y agenda.",
    price_ars: 1_500_000,
    price_usd: 1800,
    type: "proyecto",
    delivery_time: "4-6 semanas",
  },
  {
    id: "s-02",
    name: "Web app a medida",
    description: "App web con base de datos, autenticación y dashboard.",
    price_ars: 3_500_000,
    price_usd: 4000,
    type: "proyecto",
    delivery_time: "6-10 semanas",
  },
  {
    id: "s-03",
    name: "Landing + formularios",
    description: "Sitio de una página optimizado para conversión.",
    price_ars: 450_000,
    price_usd: 550,
    type: "proyecto",
    delivery_time: "1-2 semanas",
  },
  {
    id: "s-04",
    name: "Soporte mensual",
    description: "Mantenimiento, updates, bugfixes, pequeños cambios.",
    price_ars: 60_000,
    price_usd: 80,
    type: "mensual",
    delivery_time: "continuo",
  },
  {
    id: "s-05",
    name: "Consultoría IA",
    description: "Sesiones 1:1 para evaluar oportunidades de IA en tu negocio.",
    price_ars: 35_000,
    price_usd: 40,
    type: "hora",
    delivery_time: "según disponibilidad",
  },
];

export const projectFiles: ProjectFile[] = [
  { id: "f-01", project_id: "p-01", name: "Figma bot UI", url: "https://figma.com/...", type: "figma", uploaded_by: "u-marcos", created_at: "2026-02-12" },
  { id: "f-02", project_id: "p-01", name: "Repositorio backend", url: "https://github.com/me/bot-bachmann", type: "repo", uploaded_by: "u-ezra", created_at: "2026-02-14" },
  { id: "f-03", project_id: "p-02", name: "Drive cliente", url: "https://drive.google.com/...", type: "drive", uploaded_by: "u-ezra", created_at: "2026-03-05" },
];

export const decisions: Decision[] = [
  {
    id: "d-01",
    project_id: "p-01",
    title: "Usar WhatsApp Cloud API oficial",
    description: "Se descarta Twilio por costos. Meta Cloud API es más barato y estable.",
    decided_by: "u-ezra",
    created_at: "2026-02-18",
  },
  {
    id: "d-02",
    project_id: "p-02",
    title: "Stack: Next.js + Supabase",
    description: "Confirmamos stack principal para portal de proyectos.",
    decided_by: "u-ezra",
    created_at: "2026-03-06",
  },
];

export const communications: Communication[] = [
  {
    id: "com-01",
    client_id: "c-01",
    project_id: "p-01",
    subject: "Demo del bot",
    content: "Quedamos en mostrar el bot el viernes por video.",
    type: "whatsapp",
    contacted_by: "u-marcos",
    created_at: "2026-04-14",
  },
  {
    id: "com-02",
    client_id: "c-02",
    project_id: "p-02",
    subject: "Revisión wireframes",
    content: "Iván pidió ajustar tipografía en vistas de expedientes.",
    type: "email",
    contacted_by: "u-ezra",
    created_at: "2026-04-12",
  },
];

export const auditLog: AuditLog[] = [
  {
    id: "al-01",
    user_id: "u-ezra",
    action: "create",
    entity_type: "project",
    entity_id: "p-04",
    description: "Ezra creó proyecto 'Chatbot turnos Clínica Andina'",
    created_at: "2026-04-01T10:12:00Z",
  },
  {
    id: "al-02",
    user_id: "u-marcos",
    action: "update",
    entity_type: "project",
    entity_id: "p-01",
    description: "Marcos cambió la fase de 'diseno' a 'desarrollo'",
    old_value: { phase: "diseno" },
    new_value: { phase: "desarrollo" },
    created_at: "2026-04-14T16:30:00Z",
  },
  {
    id: "al-03",
    user_id: "u-ezra",
    action: "create",
    entity_type: "payment",
    entity_id: "pay-03",
    description: "Ezra registró cobro USD 1.200 del proyecto 'Portal Trama'",
    created_at: "2026-03-09T12:00:00Z",
  },
  {
    id: "al-04",
    user_id: "u-marcos",
    action: "update",
    entity_type: "task",
    entity_id: "t-06",
    description: "Marcos marcó tarea 'Configurar Supabase' como completada",
    created_at: "2026-04-09T18:20:00Z",
  },
  {
    id: "al-05",
    user_id: "u-ezra",
    action: "create",
    entity_type: "milestone",
    entity_id: "ms-03",
    description: "Ezra registró logro 'Primer cliente con mantenimiento'",
    created_at: "2026-04-05T09:00:00Z",
  },
];

export const milestones: Milestone[] = [
  {
    id: "ms-01",
    title: "Primer cliente",
    description: "Cervecería Bachmann firma el primer proyecto.",
    achieved_at: "2025-11-02",
    registered_by: "u-marcos",
    auto_generated: true,
  },
  {
    id: "ms-02",
    title: "Primer cobro en USD",
    description: "Trama paga Hito 1 del portal de proyectos.",
    achieved_at: "2026-03-09",
    registered_by: "u-ezra",
    auto_generated: true,
  },
  {
    id: "ms-03",
    title: "Primer mantenimiento renovado",
    description: "La Veleta entra en soporte y paga mes 4 consecutivo.",
    achieved_at: "2026-04-05",
    registered_by: "u-ezra",
    auto_generated: true,
  },
  {
    id: "ms-04",
    title: "Definimos stack oficial",
    description: "Next.js + Supabase + Tailwind como base para todos los proyectos.",
    achieved_at: "2026-03-06",
    registered_by: "u-ezra",
    auto_generated: false,
  },
];
